# Generated by Django 3.2.5 on 2021-12-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_billingprofile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_id',
        ),
    ]
