# Generated by Django 3.2.5 on 2021-11-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Tax_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
